# Generated by Django 2.1.3 on 2018-11-15 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tube', '0003_employee_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
